const Users = [{
  "id": 1,
  "name": "Chrissie",
  "last": "Hane",
  "password": "nW4BvjNilE",
  "email": "chane0@simplemachines.org",
  "phone": "979-938-1927",
  "diet": false,
  "location_id": 1
}, {
  "id": 2,
  "name": "Carmella",
  "last": "Heustace",
  "password": "d1cxMeRgJ",
  "email": "cheustace1@mysql.com",
  "phone": "446-423-0176",
  "diet": false,
  "location_id": 2
}, {
  "id": 3,
  "name": "Josy",
  "last": "Loade",
  "password": "FKSz51RtOiad",
  "email": "jloade2@phpbb.com",
  "phone": "470-642-8181",
  "diet": true,
  "location_id": 3
}, {
  "id": 4,
  "name": "Ariana",
  "last": "Warr",
  "password": "OkOV6g48ld",
  "email": "awarr3@moonfruit.com",
  "phone": "270-844-2864",
  "diet": true,
  "location_id": 4
}, {
  "id": 5,
  "name": "Izak",
  "last": "Lightman",
  "password": "zLP7kmpH0",
  "email": "ilightman4@princeton.edu",
  "phone": "206-305-3466",
  "diet": true,
  "location_id": 5
}, {
  "id": 6,
  "name": "Evey",
  "last": "Sheriff",
  "password": "HQGBQMAQZyMB",
  "email": "esheriff5@spiegel.de",
  "phone": "413-420-2730",
  "diet": true,
  "location_id": 6
}, {
  "id": 7,
  "name": "Arv",
  "last": "Stiger",
  "password": "86glHk",
  "email": "astiger6@aol.com",
  "phone": "435-716-9641",
  "diet": false,
  "location_id": 7
}, {
  "id": 8,
  "name": "Nancie",
  "last": "Dahmel",
  "password": "LliKEDOAq02",
  "email": "ndahmel7@webmd.com",
  "phone": "593-890-8344",
  "diet": true,
  "location_id": 8
}, {
  "id": 9,
  "name": "Martguerita",
  "last": "Foord",
  "password": "fVKq6pPJXI",
  "email": "mfoord8@tripod.com",
  "phone": "636-811-5504",
  "diet": true,
  "location_id": 9
}, {
  "id": 10,
  "name": "Fletcher",
  "last": "Graffham",
  "password": "PlGEQCIUMu1z",
  "email": "fgraffham9@epa.gov",
  "phone": "370-745-7793",
  "diet": true,
  "location_id": 10
}, {
  "id": 11,
  "name": "Norrie",
  "last": "Sigge",
  "password": "ZX9Mg9O",
  "email": "nsiggea@tumblr.com",
  "phone": "258-924-6946",
  "diet": false,
  "location_id": 11
}, {
  "id": 12,
  "name": "Eolande",
  "last": "Youdell",
  "password": "W2LdCBjZ0cZ",
  "email": "eyoudellb@house.gov",
  "phone": "377-698-8350",
  "diet": false,
  "location_id": 12
}, {
  "id": 13,
  "name": "Donnie",
  "last": "Bunnell",
  "password": "TeCOt38vjb",
  "email": "dbunnellc@telegraph.co.uk",
  "phone": "265-299-0556",
  "diet": true,
  "location_id": 13
}, {
  "id": 14,
  "name": "Clyve",
  "last": "Leversuch",
  "password": "CMko3f",
  "email": "cleversuchd@4shared.com",
  "phone": "328-796-9572",
  "diet": true,
  "location_id": 14
}, {
  "id": 15,
  "name": "Stevana",
  "last": "Redrup",
  "password": "SiZNIAS1Fejk",
  "email": "sredrupe@nps.gov",
  "phone": "780-885-0589",
  "diet": false,
  "location_id": 15
}, {
  "id": 16,
  "name": "Ibrahim",
  "last": "Spurge",
  "password": "M0QHZZuq7C",
  "email": "ispurgef@cnn.com",
  "phone": "271-740-0502",
  "diet": false,
  "location_id": 16
}, {
  "id": 17,
  "name": "Claribel",
  "last": "Geddes",
  "password": "UOVC1wYA5Xjn",
  "email": "cgeddesg@businessweek.com",
  "phone": "792-746-9921",
  "diet": true,
  "location_id": 17
}, {
  "id": 18,
  "name": "Waring",
  "last": "Loughran",
  "password": "SwRjfRCSkJ7",
  "email": "wloughranh@eepurl.com",
  "phone": "687-499-8970",
  "diet": true,
  "location_id": 18
}, {
  "id": 19,
  "name": "Mallory",
  "last": "Sellors",
  "password": "47lVyBpCS",
  "email": "msellorsi@sciencedaily.com",
  "phone": "763-408-2960",
  "diet": false,
  "location_id": 19
}, {
  "id": 20,
  "name": "Julina",
  "last": "Wyse",
  "password": "u1sVunmis0",
  "email": "jwysej@rambler.ru",
  "phone": "543-649-3858",
  "diet": true,
  "location_id": 20
}, {
  "id": 21,
  "name": "Hernando",
  "last": "Sinclar",
  "password": "jDUNT73xc",
  "email": "hsinclark@hud.gov",
  "phone": "604-517-4520",
  "diet": true,
  "location_id": 21
}, {
  "id": 22,
  "name": "Reena",
  "last": "Simpkin",
  "password": "CXX4EShPWehI",
  "email": "rsimpkinl@google.ca",
  "phone": "627-251-5492",
  "diet": true,
  "location_id": 22
}, {
  "id": 23,
  "name": "Bev",
  "last": "Bucktharp",
  "password": "H70jAX",
  "email": "bbucktharpm@aol.com",
  "phone": "985-422-0804",
  "diet": false,
  "location_id": 23
}, {
  "id": 24,
  "name": "Haven",
  "last": "Mc Comb",
  "password": "rJ0g0dlFImq",
  "email": "hmccombn@ucoz.ru",
  "phone": "141-733-3438",
  "diet": true,
  "location_id": 24
}, {
  "id": 25,
  "name": "Deni",
  "last": "Champken",
  "password": "gS1Kr6oZ",
  "email": "dchampkeno@marriott.com",
  "phone": "544-896-2207",
  "diet": true,
  "location_id": 25
}, {
  "id": 26,
  "name": "Cathrine",
  "last": "Clancy",
  "password": "Yf53ahoKsxw",
  "email": "cclancyp@redcross.org",
  "phone": "755-374-1479",
  "diet": false,
  "location_id": 26
}, {
  "id": 27,
  "name": "Beth",
  "last": "Siggs",
  "password": "I4tTGH95tO1",
  "email": "bsiggsq@drupal.org",
  "phone": "456-475-0789",
  "diet": true,
  "location_id": 27
}, {
  "id": 28,
  "name": "Brockie",
  "last": "Atkins",
  "password": "dmsp2epx",
  "email": "batkinsr@delicious.com",
  "phone": "414-636-6310",
  "diet": false,
  "location_id": 28
}]

module.exports = Users;