const Users = [{
  "name": "Ashien",
  "last": "Pickavant",
  "email": "apickavant0@geocities.jp",
  "password": "0TBf85GuPTK",
  "phone": "628-147-6636",
  "diet": false
}, {
  "name": "Nonna",
  "last": "Thorburn",
  "email": "nthorburn1@go.com",
  "password": "BkyBSuCEA",
  "phone": "719-705-6438",
  "diet": false
}, {
  "name": "Audra",
  "last": "Cuming",
  "email": "acuming2@mashable.com",
  "password": "om5hRUM",
  "phone": "397-149-2733",
  "diet": true
}, {
  "name": "Melinde",
  "last": "Vany",
  "email": "mvany3@china.com.cn",
  "password": "UyD9tWgx",
  "phone": "545-146-5305",
  "diet": false
}, {
  "name": "Arabelle",
  "last": "Rubega",
  "email": "arubega4@yahoo.com",
  "password": "EfrayocD4",
  "phone": "832-829-5856",
  "diet": false
}, {
  "name": "Goldi",
  "last": "Leeming",
  "email": "gleeming5@reddit.com",
  "password": "ZOPOS6",
  "phone": "272-226-5345",
  "diet": false
}, {
  "name": "Krissy",
  "last": "Dybell",
  "email": "kdybell6@goo.gl",
  "password": "xKPHtoE",
  "phone": "232-246-4505",
  "diet": true
}, {
  "name": "Sal",
  "last": "Double",
  "email": "sdouble7@purevolume.com",
  "password": "8qmMWNolJAq",
  "phone": "884-288-3924",
  "diet": false
}, {
  "name": "Inger",
  "last": "Blackbourn",
  "email": "iblackbourn8@51.la",
  "password": "49hIHhWU",
  "phone": "869-610-7875",
  "diet": true
}, {
  "name": "Devinne",
  "last": "Ridding",
  "email": "dridding9@independent.co.uk",
  "password": "ru8lFoBP",
  "phone": "963-627-8864",
  "diet": true
}, {
  "name": "Karen",
  "last": "Willder",
  "email": "kwilldera@bluehost.com",
  "password": "gExeHkFk7x",
  "phone": "677-225-9228",
  "diet": false
}, {
  "name": "Meghann",
  "last": "D'Alwis",
  "email": "mdalwisb@sourceforge.net",
  "password": "sB1s0y2hJ6",
  "phone": "285-894-3911",
  "diet": true
}, {
  "name": "Britteny",
  "last": "Suter",
  "email": "bsuterc@usgs.gov",
  "password": "Q8mXXUNg",
  "phone": "854-682-0510",
  "diet": false
}, {
  "name": "Addy",
  "last": "Gowthorpe",
  "email": "agowthorped@hc360.com",
  "password": "jfOWDxE",
  "phone": "575-300-4085",
  "diet": false
}, {
  "name": "Ron",
  "last": "Blackie",
  "email": "rblackiee@ezinearticles.com",
  "password": "fdXqrXJ",
  "phone": "502-730-7695",
  "diet": false
}, {
  "name": "Lind",
  "last": "Drage",
  "email": "ldragef@ning.com",
  "password": "E44WKocQlCoF",
  "phone": "317-319-9781",
  "diet": false
}, {
  "name": "Aubrie",
  "last": "Whitwell",
  "email": "awhitwellg@imgur.com",
  "password": "phiCh4b2vr",
  "phone": "265-812-8373",
  "diet": false
}, {
  "name": "Philis",
  "last": "Pain",
  "email": "ppainh@netlog.com",
  "password": "6GuEBK",
  "phone": "943-680-9718",
  "diet": true
}, {
  "name": "Xymenes",
  "last": "Carrack",
  "email": "xcarracki@ustream.tv",
  "password": "vKBlE8",
  "phone": "695-590-9265",
  "diet": false
}, {
  "name": "Jacintha",
  "last": "Casey",
  "email": "jcaseyj@nationalgeographic.com",
  "password": "QMrZcihdH8b",
  "phone": "927-643-6089",
  "diet": false
}, {
  "name": "Jehu",
  "last": "Roelofsen",
  "email": "jroelofsenk@census.gov",
  "password": "udD46tN",
  "phone": "795-205-5371",
  "diet": true
}, {
  "name": "Armando",
  "last": "Shovlin",
  "email": "ashovlinl@studiopress.com",
  "password": "0OQEDqa2",
  "phone": "138-330-5511",
  "diet": true
}, {
  "name": "Godart",
  "last": "Winkett",
  "email": "gwinkettm@psu.edu",
  "password": "iTpbuK5k0x",
  "phone": "317-145-0151",
  "diet": false
}, {
  "name": "Goraud",
  "last": "Million",
  "email": "gmillionn@netscape.com",
  "password": "WuqQEJ5U3yx",
  "phone": "860-855-2558",
  "diet": false
}, {
  "name": "Rafael",
  "last": "Flasby",
  "email": "rflasbyo@flickr.com",
  "password": "mrOhHlwbszx",
  "phone": "404-401-8008",
  "diet": false
}, {
  "name": "Hattie",
  "last": "Ryder",
  "email": "hryderp@phoca.cz",
  "password": "9Esybu",
  "phone": "949-220-4591",
  "diet": true
}, {
  "name": "Barret",
  "last": "Adkins",
  "email": "badkinsq@surveymonkey.com",
  "password": "EL9NU0H",
  "phone": "474-404-7362",
  "diet": true
}, {
  "name": "Laurie",
  "last": "Clucas",
  "email": "lclucasr@wordpress.org",
  "password": "jssuJxUXK5",
  "phone": "962-330-9026",
  "diet": false
}]

module.exports = Users;